### ISSUE TITLE
arrow entity stuck midair after chorus flower drops

### ISSUE THREAD

**Issue by WarlordWossman** [Lothrazar/ChorusArrow#2]
_Minecraft Version:_ 
1.12.2

_Forge Version:_ 
2838

_Mod Version:_ 
1.0.2

_Single Player or Server:_
singleplayer

_Describe problem (what you were doing; what happened; what should have happened):_
Arrow entities remain stuck midair after shooting chorus flowers instead of dropping down similar to when you remove a block that arrows are stuck in.
To reproduce: Just shoot chorus flowers with arrows.

_Video/images/gifs (direct upload or link):_ 
![2019-06-16_15 35 52](https://user-images.githubusercontent.com/16925725/59564944-31915380-904d-11e9-87de-11575472d05e.png)

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/arrow-harvest/files/2734234
